model:
  name: cgnetV2_deformable
  load: /content/CS517-Enhancing-License-Plate-Super-Resolution/best_model_cgnetV2_deformable_Epoch_82.pth
  args:
    in_channels: 3
    out_channels: 3

model_ocr:
  name: ocr
  args:
    load: /content/drive/MyDrive/models_ocr_pre_trained/RodoSol-SR

test_dataset:
  dataset:
    name: parallel_training
    args:
      path_split: /content/drive/MyDrive/rodosol/split_new.txt
      phase: testing

  wrapper:
    name: parallel_images_lp
    args:
      imgW: 48
      imgH: 16
      aug: False
      image_aspect_ratio: 3
      background: (0.5, 0.5, 0.5)
      test: True
  batch: 2

